// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zuaylrekibridgmrzafg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp1YXlscmVraWJyaWRnbXJ6YWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzExNjksImV4cCI6MjA3MTIwNzE2OX0._6VO2NN4sxhzVAz8a8913XQpJapgyYkXLZ-FXCQ5bQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);